### ISSUE TITLE
Azure OpenAI embeddings missing `output_vector_size`

### ISSUE THREAD

**Issue by undo76** [superlinear-ai/raglite#43]
LLMLite Azure OpenAI embedding configuration is missing the `output_vector_size` property. It makes the embeddings to fail as it is checked in RAGLite. 

I am not sure if we should rely on it in any case, as these models allow variable length (i.e. Matryoshka embeddings)

Example (OpenAI vs. Azure OpenAI) from [LiteLLM](https://github.com/BerriAI/litellm/blob/7ced9c8c0e3de866d20602c8d85056df7a76d61c/model_prices_and_context_window.json#L777):
```
    "text-embedding-3-large": {
        "max_tokens": 8191,
        "max_input_tokens": 8191,
        "output_vector_size": 3072,
        "input_cost_per_token": 0.00000013,
        "output_cost_per_token": 0.000000,
        "litellm_provider": "openai",
        "mode": "embedding"
    },
    
```

```
    "azure/text-embedding-3-large": {
        "max_tokens": 8191,
        "max_input_tokens": 8191,
        "input_cost_per_token": 0.00000013,
        "output_cost_per_token": 0.000000,
        "litellm_provider": "azure",
        "mode": "embedding"
    },
```

**Comment by lsorber** [comment]
Fixed by #44.
