### ISSUE TITLE
Inconsistent Schema Handling Between OpenAI and llama.cpp

### ISSUE THREAD

**Issue by undo76** [superlinear-ai/raglite#58]
When using different language model backends (OpenAI vs. llama.cpp) for structured data extraction, there’s an inconsistency in how schemas are handled. Specifically, OpenAI automatically adheres to the provided schema, whereas llama.cpp fails to do so unless the schema is explicitly included. Additionally, there are differences in how additionalProperties are managed, leading to potential incompatibilities.

## Example

Given the following code:
```python
def test_extract(llm: str) -> None:
    """Test extracting structured data."""
    # Set the LLM.
    config = RAGLiteConfig(llm=llm)

    # Extract structured data.
    class LoginResponse(BaseModel):
        username: str = Field(..., description="The username.")
        password: str = Field(..., description="The password. Redacted with '***'.")
        system_prompt: ClassVar[str] = "Extract the username and password from the input."

    username, password = "cypher", "steak"
    login_response = extract_with_llm(LoginResponse, f"{username} // {password}", config=config)
    # Validate the response.
    assert isinstance(login_response, LoginResponse)
    assert login_response.password == "***"
```

If we don't include the schema in the prompt. 

OpenAI:
- Automatically includes and adheres to the schema.
- Successfully redacts the password.

llama.cpp:
- Adheres to the schema, but not following the instructions in the descriptions.
- Does not include the schema intrinsically.
- Fails to redact the password unless the schema is explicitly provided.

If we include always the schema in the prompt, OpenAI sometimes fails to adhere to the schema consistently unless `strict` is set to `true`.
	
Current Behavior:
- OpenAI requires explicit additionalProperties=false in strict mode.
- llama.cpp defaults additionalProperties=false, which is compatible but not aligned with OpenAI’s requirements. ( https://github.com/ggerganov/llama.cpp/tree/master/grammars)

**Comment by lsorber** [comment]
I think the choice we're making now is pretty reasonable:

1. For OpenAI-like models:
    a. We don't include the schema in the system prompt (because it doesn't need it).
    b. We make strict mode optional, and False by default (because only supports a subset of JSON schema features).
2. For llama.cpp models:
    a. We include the schema in the system prompt (because otherwise the LLM cannot 'plan' what output to generate).
    b. We ignore strict mode (because it doesn't support it).

Would you change any of that, or are we missing something?

**Comment by undo76** [comment]
Indeed. I was missing the second condition. It's fine for me
