### ISSUE TITLE
 No such option: --db_url Did you mean --db-url? 

### ISSUE THREAD

**Issue by rafikoham** [superlinear-ai/raglite#64]
Maybe you just update the flag because there's no way to run the command raglit chainlit with the --db_url as mentionned !

**Comment by rafikoham** [comment]
<img width="554" alt="image" src="https://github.com/user-attachments/assets/06b9ed68-c65a-4d05-8ae4-25fb41cb39a7" />

**Comment by lsorber** [comment]
This was a documentation error and was fixed in a recent release! It should indeed be `--db-url`.
